"""Panel copy and code patches for the YuE2-3B atlas (anchored on the engine's own text).

Every entry is (whole line to replace, replacement line). Both sides are authored as triple-quoted
Python strings so that JS quotes need no Python escaping at all: the text here lands in the page as
raw JS source, and a stray backslash before a quote is a syntax error in the browser.
"""

R = []
R.append(("""<meta name="description" content="Offline Preact and WebGL2 architecture atlas for DeepSeek""",
          """<meta name="description" content="Offline Preact and WebGL2 architecture atlas for m-a-p/YuE2-3B: a music-generation backbone that is a Mixture of Transformers, 28 layers each holding an autoregressive stack (score and semantic tokens) and a non-autoregressive stack (acoustic latents), VAE bridges into a 64-dim latent space, a flow-matching timestep embedder and a 184,704-row untied vocabulary, measured across BF16, FP8 and NVFP4.">"""))
R.append(("""<title>DeepSeek V4.1 Flash - Tensor Atlas v4</title>""",
          """<title>YuE2-3B - Tensor Atlas v4</title>"""))
R.append(("""DeepSeek Model Atlas requires JavaScript""",
          """<div id="root"></div><noscript><div style="padding:40px;color:#d7e6ff;font-family:monospace">YuE2-3B Model Atlas requires JavaScript. Everything needed is already embedded in this file. Enable JavaScript and reload.</div></noscript>"""))
R.append(("""/* DeepSeek V4.1 Flash Atlas. Model facts from the supplied configs and""",
          """/* YuE2-3B Atlas. Architecture from the published config of m-a-p/YuE2-3B;"""))
R.append(("""DeepSeek's reference source; byte totals are schema-derived, not shard-audited. */""",
          """every byte was measured from the safetensors headers of the BF16, FP8 and NVFP4 checkpoints. */"""))
R.append(("""ONE CHECKPOINT / ONE CONTINUOUS FORWARD PASS""",
          """<div class="intro-kicker">ONE ARCHITECTURE / THREE PUBLISHED PRECISIONS</div><h2 class="editorial">7.26 GB.<br/><em>Two transformers per layer.</em></h2><p class="lede">YuE2-3B writes music the way its card describes it: an autoregressive stack emits the score and the semantic tokens, a non-autoregressive stack models the acoustic latents in parallel, and two VAE bridges hand 64-dim latents to a separate decoder.</p>"""))
R.append(("""Decode execution order""",
          """<div class="decode-path" aria-label="Decode execution order"><span>Embedding</span><i>\\u2192</i><span>L00\\u2013L27<small>AR + NAR each</small></span><i>\\u2192</i><span>llm2vae<small>2048 \\u2192 64</small></span><i>\\u2192</i><span>VAE decode<small>separate checkpoint</small></span></div>"""))
R.append(("""Same block pattern, different weights""",
          """<${Section} title="One layer, two complete transformers"><p class="fine">Every one of the 28 layers contains an <b>autoregressive</b> block (self_attn plus a 2048 \\u2192 6144 \\u2192 2048 FFN) and a <b>non-autoregressive</b> block (nar_self_attn plus nar_mlp) with its own norms. They share the residual width and the vocabulary, not the matrices.</p><p class="fine">Nothing in this stack is recurrent: all 28 layers keep a KV cache at 8 KV heads and head_dim 128, which is 114,688 bytes per token at BF16. The latents travel up to 24,576 frames deep, so the timeline \\u2014 not a constant state \\u2014 is the cost.</p><button class="text-link" onClick=${()=>this.setLayout(s.layout==='tower'?'split':'tower')}>${s.layout==='tower'?'Separate the two layer ranges':'Merge into one numbered tower'} <${Icon} name="arrow" size=${14}/></button><//>"""))
R.append(("""What actually changes at the boundary?""",
          """<${Section} title="What actually changes between the halves?"><p class="fine">Nothing architectural: the split is a reading aid. Every layer in both halves carries the AR block, the NAR block, their two FFNs and four norms \\u2014 22 tensors, byte-identical from L00 to L27.</p><p class="fine">What differs between the three checkpoints on this page is only precision and bookkeeping: the reference stores everything at BF16, the FP8 build writes e4m3 weights with a per-tensor scale beside each, and the NVFP4 build stores weights packed at 4 bits with both a block scale and a global scale.</p><//>"""))
R.append(("""Then why does prefill sometimes show only half?""",
          """<details class="assumptions"><summary>Why is NVFP4 only a third of the BF16 file?</summary><p>The vocabulary resists quantisation: the embedding and the head are 1.51 GB of the 7.26 GB reference, and both community builds leave them (and the norms) at higher precision, so the converted mass is mostly the two transformer stacks.</p><a href=${SOURCE_BASE} target="_blank" rel="noopener noreferrer">Read the YuE2-3B model card</a></details>"""))
R.append(("""<small>BACKBONE</small>""",
          """<div class="stat-grid"><div><small>PARAMETERS</small><strong>3.5<span>B stored</span></strong></div><div><small>LAYERS</small><strong>28<span>x AR + NAR</span></strong></div><div><small>VOCABULARY</small><strong>184,704<span>untied</span></strong></div><div><small>LATENT FRAMES</small><strong>24,576<span>max</span></strong></div></div>"""))
R.append(("""The model card describes an optimized prefill""",
          """<${Note}>The three payloads on this page are sums of tensor byte ranges read from the published shard headers of the BF16 reference and of the two community quantised builds. Parameter, training and audio-quality claims come from the YuE2-3B model card.<//>"""))
R.append(("""Read the architecture / click to unfold""",
          """<${Section} title="Read the architecture / click to unfold" tag="28 layers"><div class="mode-legend">${[['ar_attn','28','AR attention'],['nar_attn','28','NAR attention'],['ar_ffn','28','AR feed-forward'],['nar_ffn','28','NAR feed-forward']].map(([key,n,label])=>html`<button class="mode-key" onClick=${()=>this.setView('storage')}><i style=${{background:TC[key]}}/><b>${n}</b><span>${label}</span></button>`)}</div>"""))
R.append(("""label="Hidden width / mHC streams\"""",
          """<${Fact} label="Hidden width" value="2,048"/><${Fact} label="Attention" value="16 Q / 8 KV heads at 128 dims"/><${Fact} label="Per layer" value="AR block + NAR block"/><${Fact} label="FFN width" value="6,144 (SwiGLU, twice per layer)"/><${Fact} label="Vocabulary" value="184,704 untied rows"/><${Fact} label="Latent space" value="64 dims via the VAE bridges" color=${COL.bridge}/><p class="fine">Layer numbers are zero-based. The cache view measures 8 KV heads across all 28 layers, because this model has no recurrent layers at all.</p><//>"""))
R.append(("""Guided tour: Full, Reindex and Reuse""",
          """<button class="outline-btn full-width" onClick=${()=>this.patch({tab:'guide'})}>Guided tour: a block, the bridges, the vocabulary <${Icon} name="arrow" size=${14}/></button><${Section} title="Beyond the blocks">${[['vae','B','VAE bridges','llm2vae / vae2llm \\u00b7 2048 \\u2194 64',COL.bridge],['latent','P','Latent position embedding','24,576 frames \\u00b7 100.7 MB',COL.latent],['time','T','Timestep embedder','flow matching \\u00b7 16.8 MB',COL.time]].map(([id,letter,title,sub,c])=>html`<button class="feature-link" onClick=${()=>this.select(id)}><span class="feature-icon" style=${{color:c}}>${letter}</span><span><b>${title}</b><small>${sub}</small></span><${Icon} name="chevron" size=${14}/></button>`)}<//>"""))
R.append(("""What the volumes mean""",
          """<${Section} title="What the volumes mean" tag="Storage, not VRAM"><${Fact} label="Logical values in this inventory" value=${fmtP(TOTAL_P)}/><${Fact} label=${MODE_INFO[s.precision].label+' payload'} value=${bytes(TOTALS[s.precision],s.binary)} color=${MODE_INFO[s.precision].color}/><p class="fine">Solids use one common scale: 1 cubic world unit = 1 GB. Payloads are the measured shard headers, not shape estimates. The separate VAE decoder (0.531 GB) is not part of these totals and is named in Sources.</p><button class="text-link" onClick=${()=>this.setView('storage')}>Inspect the byte ledger <${Icon} name="arrow" size=${15}/></button><//>"""))
R.append(("""Decode step ${m.index+1} of 40.""",
          """${m.mode&&html`<p class="layer-execution"><b>Block ${String(m.index).padStart(2,'0')} of 28.</b> Two complete transformers: an autoregressive stack that writes the score and the semantic tokens, and a non-autoregressive stack that models the acoustic latents \\u2014 22 tensors, identical in every layer.</p>`}"""))
R.append(("""['Main attention queries'""",
          """['AR attention','Own weights','16 query heads over 8 KV heads at head_dim 128, with per-head q and k norms.',TC.ar_attn,'own'],"""))
R.append(("""['Local SWA KV'""",
          """['NAR attention','Own weights','A second q/k/v/o set with its own norms: the latent stack, conditioned on the flow-matching timestep.',TC.nar_attn,'own'],"""))
R.append(("""['Global main KV'""",
          """['KV cache','Own cache','8 KV heads x 128 dims x (k+v) x 2 B = 4,096 bytes per token per layer, and every layer has one.',TC.kv,'own'],"""))
R.append(("""['Indexer keys'""",
          """['Timestep conditioning','Shared','time_embedder.mlp turns the flow-matching timestep into 2048 dims and feeds the latent stack.',TC.time,'shared'],"""))
R.append(("""['Top-512 selection'""",
          """['Bridges','Shared','llm2vae projects to the 64-dim latent space; vae2llm projects back. Tiny, and the only tensors that leave the language width.',TC.bridge,'shared']"""))
R.append(("""Borrowed objects are runtime memory""",
          """<p class="fine">The cache is the only growing object here: 4,096 bytes per token per layer across 28 layers, and the context is measured in latent frames (up to 24,576).</p><//>`}"""))
R.append(("""title="Inside one expert\"""",
          """${isLayer&&html`<${Section} title="Inside the block" tag=${"AR + NAR"}><div class="expert-equation">AR : self_attn = 16 Q / 8 KV at 128 dims<br/>AR : mlp = 2048 \\u2192 6144 \\u2192 2048 (SwiGLU)<br/>NAR: nar_self_attn + nar_mlp, its own matrices<br/>4 norms per layer, 22 tensors in total</div><${Fact} label="One block / logical parameters" value=${fmtP(sumP(m.ws))}/><${Fact} label="Block bytes at ${MODE_INFO[s.precision].label}" value=${bytes(sumB(m.ws,s.precision),s.binary)}/><${Fact} label="Largest tensors in the block" value="FFN 25.2 MB each at BF16"/><p class="fine">Both halves are stored per layer \\u2014 there is no expert bank and no shared block to fold, so every byte in the block belongs to the layer you are looking at.</p><button class="outline-btn full-width" onClick=${()=>this.patch({expertView:!s.expertView,tensor:null,hoverTensor:null})}>${s.expertView?'Return to named tensor banks':'Unfold the block'} <${Icon} name="expand" size=${14}/></button><//>`}"""))
R.append(("""${m.id[0]==='E'&&html`<${Section} title="From token IDs to a gated lookup">""",
          """${(m.id==='embed'||m.id==='vae'||m.id==='latent'||m.id==='time')&&html`${m.id==='embed'?html`<${Section} title="Why the vocabulary is the biggest thing here"><div class="expert-equation">embed_tokens [184,704 x 2048] 756.5 MB at BF16<br/>lm_head [184,704 x 2048] 756.5 MB at BF16<br/>untied: two independent tables<br/>1.51 GB of the 7.26 GB file (21%)</div><p class="fine">Both tables cover text, score and semantic audio tokens, and the quantised builds keep both at higher precision, which is why those files shrink faster than their bit width alone suggests.</p><//>`:html`<${Section} title="The parts that are not a transformer"><${Fact} label="llm2vae" value="2048 \\u2192 64 latent dims"/><${Fact} label="vae2llm" value="64 \\u2192 2048"/><${Fact} label="Latent positions" value="24,576 x 2048 = 100.7 MB at BF16"/><${Fact} label="Timestep embedder" value="2 linear layers, 16.8 MB at BF16"/><p class="fine">Four modules turn a language backbone into a music model: the bridges move between the 2048-wide language space and the 64-dim latent space of the separate VAE, the position table covers the whole latent timeline, and the timestep embedder tells the latent stack where it is on the flow-matching trajectory.</p><//>`}`}"""))
R.append(("""Images meet the language model""",
          """${isLayer&&html`<${Section} title="Same weights, different payload">${Object.keys(MODE_INFO).map(mode=>{const b=sumB(m.ws,mode);return html`<div class="ledger-bar"><div><span>${MODE_INFO[mode].label}</span><b>${bytes(b,s.binary)}</b></div><span><i style=${{width:b/sumB(m.ws,'bf16')*100+'%',background:MODE_INFO[mode].color,opacity:mode===s.precision?1:.35}}/></span></div>`;})}<p class="fine">The FP8 build quantises the linear weights with a per-tensor scale; the NVFP4 build packs weights to 4 bits and stores a block scale plus a global scale for each. The embedding, the head and the norms stay wide in both, so the file stops shrinking where the vocabulary begins.</p><//>`}"""))
R.append(("""Follow the data.<br/><em>Read the weights.</em>""",
          """renderGuide(){return html`<div><div class="inspect-path">A READING GUIDE TO THE ANIMATION</div><h2 class="editorial">Follow the data.<br/><em>Read the weights.</em></h2><p class="lede">The solids are learned tensors. The moving lights are explanatory signals. Do not read the size of a weight as its runtime workload.</p>"""))
R.append(("""Start with a Reuse layer""",
          """<${Section} title="Start with one block"><p class="guide-copy">Open L00. Twenty-two tensors: the AR stack (attention plus a 6144-wide FFN), the NAR stack (its own attention and FFN), and four norms. Both halves see the same 2048-wide residual stream and the same vocabulary, but they never share a matrix.</p><button class="outline-btn full-width" onClick=${()=>{this.select('L0');this.patch({tab:'inspect'});}}>Open L00: the first Mixture-of-Transformers block</button><//>"""))
R.append(("""Compare a Full layer""",
          """<${Section} title="Compare a deep block"><p class="guide-copy">Now open L27. Byte for byte it is the same block as L00 \\u2014 that is the point of a Mixture of Transformers: depth changes the weights, never the shape.</p><button class="outline-btn full-width" onClick=${()=>{this.select('L27');this.patch({tab:'inspect'});}}>Open L27: the last block</button><//>"""))
R.append(("""Cross the encoder-decoder boundary""",
          """<${Section} title="Where the 7.26 GB lives"><p class="guide-copy">The 28 blocks are 5.75 GB of the reference. The vocabulary is the next biggest thing: 1.51 GB for the embedding and the head, untied. Then the latent position table (100.7 MB) and the timestep embedder (16.8 MB).</p><button class="outline-btn full-width" onClick=${()=>{this.select('embed');this.patch({tab:'inspect'});}}>Open the embedding</button><//>"""))
R.append(("""Same memory, a different search""",
          """<${Section} title="Then look at the seam"><p class="guide-copy">Open the bridges: llm2vae (2048 \\u2192 64) and vae2llm (64 \\u2192 2048) are a few hundred kilobytes together, and they are the only place where this checkpoint touches the VAE latent space. The decoder itself is a separate 0.531 GB repository.</p><button class="outline-btn full-width" onClick=${()=>{this.select('vae');this.patch({tab:'inspect'});}}>Open the VAE bridges</button><//>"""))
R.append(("""Three distinctions worth keeping""",
          """<${Section} title="Three distinctions worth keeping"><div class="layer-story"><h3>Two transformers, one layer.</h3><p>The AR and NAR blocks live side by side in the same 28 layers. Reading one block without the other misses half of what a layer computes.</p><h3>An untied vocabulary is a real cost.</h3><p>184,704 rows appear twice: 1.51 GB at BF16, 21% of the file. The quantised builds keep both wide.</p><h3>A quantiser ignores more than it converts.</h3><p>FP8 and NVFP4 both leave the embedding, the head and the norms at higher precision. Read the ledger, not the bit width.</p></div><//>"""))
R.append(("""Why NVFP4 grows here""",
          """<${Section} title="Three precisions, one architecture"><div class="equation"><span>BF16</span><code>2 B / parameter</code><span>FP8</span><code>1 B + per-tensor scale</code><span>NVFP4</span><code>0.5 B + block and global scales</code></div><${Fact} label="FP8 saves" value=${bytes(FP8_DELTA,s.binary)} color=${COL.dec}/><${Fact} label="NVFP4 saves" value=${bytes(NV_DELTA,s.binary)} color=${COL.nar_attn}/><p class="fine">Measured, not projected: 7.2614 GB becomes 2.9238 GB as e4m3 with per-tensor scales, and 2.3061 GB as 4-bit packed weights carrying both a block scale and a global scale each. Both builds keep the embedding, the head and the norms out of the conversion.</p><//>"""))
R.append(("""Accounting assumptions and limits""",
          """<details class="assumptions"><summary>Accounting assumptions and limits</summary><p>Tensor payload only: shard headers, file padding and exporter metadata are excluded, so these are not download sizes.</p><p>Every quantisation sidecar (weight_scale, weight_global_scale, weight_packed) is folded into the weight it describes, so all three modes list the same logical tensors even though the BF16 shard holds 628 tensors, the FP8 build 507 and the NVFP4 build 703.</p><p>The separate VAE decoder (m-a-p/YuE2-Vae, 0.531 GB) is not part of this checkpoint and is not counted in any total on this page. Cache figures are arithmetic from the published shapes, not measured device memory.</p></details></div>`;}"""))
R.append(("""COMPRESSED SPARSE ATTENTION 2""",
          """renderCache(){const s=this.state,n=s.context,full=n*KV_FULL_PER_TOKEN;return html`<div><div class="inspect-path">CONTEXT COST / NO RECURRENT LAYERS</div><h2 class="editorial">Twenty-eight.<br/><em>All of them cache.</em></h2><p class="lede">Every layer keeps a KV cache; nothing in this model is constant-size. What is unusual is that the context is measured in latent frames, not text tokens.</p><div class="storage-total cache-total"><small>KV CACHE / LATENT FRAME</small><strong>114,688 <em>bytes</em></strong><span>28 layers x 8 KV heads x 128 dims x (k+v) x 2 bytes</span></div>"""))
R.append(("""title="Stretch the context" tag="UP TO 1,048,576\"""",
          """<${Section} title="Stretch the timeline" tag="UP TO 24,576 FRAMES"><label class="range-title" for="context-number">Latent frames <input id="context-number" type="number" min="128" max="24576" step="128" value=${n} onChange=${e=>{const v=Number(e.target.value);this.patch({context:clamp(Number.isFinite(v)?Math.round(v):128,128,24576)});}}/></label><input class="slider" aria-label="Latent frame count logarithmic slider" type="range" min="7" max="15" step="0.05" value=${Math.log2(n)} onInput=${e=>this.patch({context:clamp(Math.round(2**Number(e.target.value)),128,24576)})}/><div class="range-ends"><span>128</span><span>2K</span><span>24K</span></div><div class="preset-row">${[2048,8192,16384,24576].map(v=>html`<button class=${n===v?'active':''} onClick=${()=>this.patch({context:v})}>${v===24576?'24K':v/1024+'K'}</button>`)}</div><${Fact} label="KV cache at this length" value=${bytes(full,s.binary)} color=${COL.ar_attn}/><${Fact} label="Recurrent state" value="none \\u2014 every layer caches" color=${COL.nar_attn}/><p class="fine">114,688 bytes per latent frame at BF16: 28 layers x 8 KV heads x 128 dims x two tensors x two bytes. At the maximum 24,576 frames the cache alone is 2.82 GB on top of the weights.</p><//>"""))
R.append(("""Where 890 comes from""",
          """<${Section} title="Where these numbers come from"><div class="equation"><span>PER LAYER / FRAME</span><code>2 x 8 x 128 x 2 B = 4,096 B</code><span>ALL 28 / FRAME</span><code>4,096 x 28 = 114,688 B</code><span>AT 24,576 FRAMES</span><code>2.82 GB at BF16</code></div><p class="fine">Arithmetic from the published shapes. The latent position table sets the ceiling: 24,576 frames is the longest timeline this checkpoint was built to read.</p><//>"""))
R.append(("""Hierarchical sparse indexer""",
          """<${Section} title="What the quantised builds actually cost" tag="MEASURED"><${Fact} label="BF16" value=${bytes(TOTALS.bf16,s.binary)+' / 628 tensors'}/><${Fact} label="FP8" value=${bytes(TOTALS.fp8,s.binary)+' / 507 tensors'}/><${Fact} label="NVFP4" value=${bytes(TOTALS.nvfp4,s.binary)+' / 703 tensors'}/><${Fact} label="Kept wide" value="embedding, head, norms"/><${Fact} label="Not counted here" value="the 0.531 GB VAE decoder"/><p class="fine">More tensors can mean a smaller file: the NVFP4 build stores a block scale and a global scale for every weight it packs, so its tensor count is the highest of the three while its payload is the lowest.</p><//><${Note} color=${COL.ar_attn}>Cache figures are arithmetic from the published config, not measured device memory. The runtime also holds activations and the flow-matching state, none of which are checkpoint bytes.<//></div>`;}"""))
R.append(("""REPORTED EVALUATIONS / NATIVE MODEL""",
          """renderBench(){const s=this.state,b=BENCH[s.bench];return html`<div><div class="inspect-path">PUBLISHER-REPORTED LEADERBOARD / AS PUBLISHED</div><h2 class="editorial">Bytes,<br/><em>not scores.</em></h2><p class="lede">YuE2-3B is a music model: it has no row in the comparison set below, which is the published leaderboard the original atlas page carries. This page measures bytes and claims no scores of its own.</p><label class="field-label">Compare a benchmark<select value=${s.bench} onChange=${e=>this.patch({bench:Number(e.target.value)})}>${BENCH.map((r,i)=>html`<option value=${i}>${r[0]}</option>`)}</select></label><p class="card-lede" style="margin:2px 0 0">This comparison set is the frontier leaderboard the original atlas page collected — this checkpoint is not in it, so rows above read &ldquo;Not reported&rdquo; wherever its card publishes nothing. Its own published figures are in the publisher-card table at the bottom of this panel.</p><div class="benchmark-chart">${BENCH_MODELS.map((name,i)=>html`<div class=${'benchmark-row'+(i===0?' featured':'')}><div><span>${name}</span><b>${b[2][i]===null?(i===0?'n/a \u2014 music model':'Not reported'):b[2][i].toFixed(1)}</b></div><div class="bench-track"><i style=${{width:(b[2][i]||0)+'%',background:i===0?COL.dec:COL.enc,opacity:i===0?1:(b[2][i]===null?0.15:0.9)}}/></div></div>`)}</div><p class="fine">${b[0]} / ${b[1]}. Publisher-reported values on each benchmark's own scale, reproduced from the original atlas page's collection; nothing here was measured or evaluated by this page.</p><div class="card-bench"><div class="inspect-path">PUBLISHER CARD / THIS CHECKPOINT</div><p class="card-lede">Every benchmark this checkpoint&rsquo;s own card reports &mdash; music quality and song identity metrics, which is what this model is for; the LLM suite above does not apply to it. Figures are reproduced unchanged.</p>${CARD_BENCH.tables.map(t=>html`<div class="card-scroll"><div class="card-title">${t.title}</div><table class="card-table"><thead><tr>${t.headers.map(h=>html`<th>${h}</th>`)}</tr></thead><tbody>${t.rows.map(r=>r[0].startsWith("== ")?html`<tr class="sec"><td colSpan=${t.headers.length}>${r[0].slice(3)}</td></tr>`:html`<tr>${r.map((c,i)=>html`<td class=${i===0?"lbl":(i===1?"num own":"num")}>${c}</td>`)}</tr>`)}</tbody></table></div>`)}<p class="card-lede" style="margin-top:10px">${CARD_BENCH.note}</p><p class="fine">Source: <a href="https://huggingface.co/${CARD_BENCH.src}" target="_blank" rel="noopener">${CARD_BENCH.src}</a> model card, retrieved 2026-09-15. Values are the publisher&rsquo;s; this page measures bytes and adds no numbers.</p></div>"""))
R.append(("""Evaluation conditions""",
          """<${Section} title="What this page does not do"><${Fact} label="Measured" value="tensor payloads from shard headers"/><${Fact} label="Not measured" value="audio quality, throughput, memory use"/><${Fact} label="Benchmark rows" value="published leaderboard, other models"/><${Fact} label="Model card" value="the authority for capabilities"/><p class="fine">An atlas is an accounting document. It can tell you that the vocabulary is 21% of the file and that NVFP4 keeps it wide; it cannot tell you whether the song sounds right.</p><//>"""))
R.append(("""Reasoning is an API setting""",
          """<${Section} title="What the quantised builds trade away"><label class="range-title">linear weights stored at 4-bit <output>${(100-s.effort*.8).toFixed(0)}%</output></label><input class="slider" type="range" min="1" max="100" value=${s.effort} aria-label="Illustrative precision trade-off" onInput=${e=>this.patch({effort:Number(e.target.value)})}/><pre class="small-code">${JSON.stringify({bf16_GB:7.2614,fp8_GB:2.9238,nvfp4_GB:2.3061,kept_wide:['model.embed_tokens','lm_head','*norm*'],vae_decoder_GB:0.531},null,2)}</pre><p class="fine">A slider that only illustrates a trade-off: the more of the file you convert, the more the tensors that resist conversion matter.</p><//></div>`;}"""))
R.append(("""PROVENANCE / SEPTEMBER 10, 2026""",
          """renderSources(){return html`<div><div class="inspect-path">PROVENANCE / MEASURED FROM PUBLISHED SHARDS</div><h2 class="editorial">Trace every<br/><em>assumption.</em></h2><p class="lede">The card supplies the claims. The config supplies the shapes. The shard headers supply the bytes \\u2014 all three modes here were read over HTTP Range, not estimated.</p><div class="source-status"><i/> Offline app / no runtime requests</div>"""))
R.append(("""title="The supplied NVFP4 recipe"><p class="fine">The second configuration was supplied in this conversation.""",
          """<${Section} title="What each repository actually contains"><p class="fine">The reference is one 7.26 GB shard of 628 BF16 tensors: both transformer stacks of all 28 layers, the untied vocabulary, the VAE bridges, the latent position table and the timestep embedder. The FP8 build converts the linear weights to e4m3 with a per-tensor scale. The NVFP4 build packs weights to 4 bits and stores a block scale plus a global scale beside each, which is why it has the most tensors and the smallest payload.</p><${Fact} label="BF16 reference" value=${bytes(TOTALS.bf16,s.binary)+' / 1 shard'}/><${Fact} label="FP8 build" value=${bytes(TOTALS.fp8,s.binary)+' / 1 shard'}/><${Fact} label="NVFP4 build" value=${bytes(TOTALS.nvfp4,s.binary)+' / 1 shard'}/><${Fact} label="VAE decoder" value="0.531 GB / separate repo, not counted"/><//>"""))
R.append(("""Tower, split and execution""",
          """<${Section} title="Tower, split and the three modes"><p class="fine">The tower is a logical layer-order view, not a map of safetensors byte offsets. Splitting moves the same 28 blocks plus the vocabulary, the bridges, the latent table and the timestep embedder into two reading groups; both layouts use the exact same tensor inventory.</p><p class="fine">The animation walks Embed \\u2192 AR stack \\u2192 NAR stack \\u2192 Bridge \\u2192 Decode: the untied vocabulary, the autoregressive half that writes the score, the non-autoregressive half that models latents under a flow-matching timestep, the 64-dim bridge, and the separate VAE decoder. Nothing here executes a model.</p><p class="fine">Training mode is a schematic of the quantisation recipe, not the authors' training code.</p><//>"""))
R.append(("""Interpretation rules""",
          """<${Section} title="Interpretation rules"><p class="fine">The measured total is ${fmtP(TOTAL_P)} stored logical values, audited tensor by tensor from the shard headers of the three repositories.</p><p class="fine">Routing, fetch, compute and draft animations in the engine shell are explanatory. No inference runs. The timeline is not a latency chart and no weight data is bundled in this HTML.</p><p class="fine">Volumes, not footprint areas: unfolding the block conserves modelled mass, and zooming never alters the byte scale. Cache figures are arithmetic from published shapes, not measured device memory.</p><//>"""))
R.append(("""DEEPSEEK MODEL ATLAS""",
          """renderModal(){const s=this.state;if(!s.modal)return null;let title={help:'Explore the model',config:'Embedded configurations',audit:'Safetensors header audit',credits:'Credits & licenses'}[s.modal];return html`<div class="modal-backdrop" onClick=${e=>{if(e.target===e.currentTarget)this.patch({modal:null});}}><div class=${'modal '+(s.modal==='config'?'wide':'')} role="dialog" aria-modal="true" aria-label=${title}><div class="modal-head"><div><div class="eyebrow">YUE2-3B MODEL ATLAS</div><h2>${title}</h2></div><button class="icon-button" aria-label="Close dialog" onClick=${()=>this.patch({modal:null})}><${Icon} name="close"/></button></div><div class="modal-body">"""))
R.append(("""['P','Cycle native / NVFP4 / BF16']""",
          """${s.modal==='help'&&html`<p class="lede">A file to keep, inspect and share. Everything needed to render the atlas is embedded.</p><div class="help-grid">${[['V','Merge tower / separate the two reading groups'],['B / T','Hide inspector / animation panel'],['+ / -','Increase / decrease all text'],['Drag','Orbit the model'],['Right-drag / Shift-drag','Pan in camera space'],['Wheel / pinch','Zoom without changing scale'],['Click a layer','Open named weight tensors'],['Click a labeled weight','Pin its role, shape and bytes'],['F / X','Columns or floor / banks or block details'],['[ / ]',"Walk the layer's tensor list"],['R / double-click','Reset the camera'],['P','Cycle BF16 / FP8 / NVFP4'],['Space','Pause or resume the story'],['Up / Down','Previous or next module'],['L / K','Toggle labels / flow paths'],['1 / 2 / 3','Architecture / Storage / Context']].map(([k,v])=>html`<div><kbd>${k}</kbd><span>${v}</span></div>`)}</div><${Note}>The animation starts in Compute and loops that phase; choose another phase or turn off Loop phase to play the whole story. Tower order is not disk order; Split moves the same objects. Training mode is a schematic of the quantisation recipe. Routing is synthetic. Solids represent measured stored bytes, not device utilisation or throughput.<//><button class="outline-btn full-width" onClick=${()=>this.patch({modal:'audit'})}>Check exact bytes from local checkpoint headers</button>`}"""))
R.append(("""Full supplied fields.""",
          """${s.modal==='config'&&html`<div class="config-switch">${['bf16','fp8','nvfp4'].map(m=>html`<button class=${(s.configMode||'bf16')===m?'active':''} onClick=${()=>this.patch({configMode:m})}>${m==='bf16'?'YuE2-3B reference':m==='fp8'?'FP8 build':'NVFP4 build'}</button>`)}</div><p class="fine">The published configs, embedded field for field. The reference tab is the model's own config; the FP8 and NVFP4 tabs are the community quantisation configs, which are saved under an upstream arch tag \\u2014 the tensor layout is what this atlas folds, not the label.</p><pre class="config-code">${JSON.stringify(s.configMode==='nvfp4'?NV_CONFIG:s.configMode==='fp8'?FP8_CONFIG:CFG,null,2)}</pre><button class="outline-btn" onClick=${()=>safeDownload((s.configMode||'bf16')+'-config.json',JSON.stringify(s.configMode==='nvfp4'?NV_CONFIG:s.configMode==='fp8'?FP8_CONFIG:CFG,null,2))}><${Icon} name="download" size=${16}/> Save config.json</button>`}"""))
R.append(("""DSpark draft stages""",
          """<div class="workspace"><nav class="layer-rail" aria-label="Model modules"><button class=${'rail-special'+(s.selected==='time'?' selected':'')} title="Timestep embedder" onClick=${()=>{this.patch({view:'architecture'});this.select('time');}}>T</button><div class="rail-caption">BRIDGE</div><div class="rail-layers">${[...LAYERS].reverse().map(m=>html`<button key=${m.id} aria-label=${m.label} class=${'rail-layer '+(s.selected===m.id?'selected':'')} style=${{'--layer-color':COL.ar_attn}} onClick=${()=>{if(s.view!=='architecture')this.patch({view:'architecture'});this.select(m.id);}} title=${m.label+' / AR + NAR'}><span>${String(m.index).padStart(2,'0')}</span><i/></button>`)}</div><div class="rail-caption">VAE</div><button class=${'rail-special'+(s.selected==='vae'?' selected':'')} title="VAE bridges" onClick=${()=>{this.patch({view:'architecture'});this.select('vae');}}>B</button></nav>"""))
R.append(("""global KV payload""",
          """<div class="scene-scale"><span class="scale-glyph"/><span>1 cubic unit = 1 GB <em>${s.view==='cache'?'context memory arithmetic':'audited weight payload'} / ${this.engine&&this.engine.renderer.software?'CPU 3D':'WebGL2'}</em></span></div><div class="scene-legend">${(s.view==='cache'?[['ar_attn','KV cache'],['nar_attn','all 28 layers']]:s.view==='storage'?[['ar_attn','AR attention'],['nar_attn','NAR attention'],['ar_ffn','AR FFN'],['nar_ffn','NAR FFN'],['vocab','Vocabulary']]:[['ar_attn','AR block'],['nar_attn','NAR block']]).map(([key,l])=>html`<span><i style=${{background:TC[key]||COL[key]}}/>${l}</span>`)}</div>"""))
R.append(("""DSPARK / FIVE-TOKEN DRAFT""",
          """${s.view==='architecture'&&s.activity==='inference'&&s.selected==='time'&&html`<div class="draft-diagram"><div><b>FLOW MATCHING / LATENT TIMELINE</b><small>time_embedder conditions the NAR stack on the timestep</small></div><div class="draft-cells">${[.98,.94,.87,.62,.41].map((confidence,i)=>{let t=(i+1)/5,stage=t<0.3?'noisy':t<0.7?'mid':'clean';return html`<div class=${'draft-cell '+stage}><small>step ${i+1}</small><b>${t.toFixed(2)}</b><span>${stage}</span></div>`;})}</div><p>Schematic; the flow trajectory is not simulated.</p></div>`}"""))
R.append(("""function fontPreference(){""",
          """function fontPreference(){try{const n=Number(localStorage.getItem('yue2-atlas-font'));return Number.isFinite(n)&&n>=.85&&n<=1.5?n:1;}catch(_){return 1;}}"""))
R.append(("""componentDidUpdate(prevProps,prevState)""",
          """componentDidUpdate(prevProps,prevState){if(prevState&&prevState.fontScale!==this.state.fontScale){try{localStorage.setItem('yue2-atlas-font',String(this.state.fontScale));}catch(_){}}if(this.engine)this.engine.sync(this.state);if(prevState&&(prevState.selected!==this.state.selected||prevState.view!==this.state.view||prevState.tab!==this.state.tab)&&this.panelRef.current)this.panelRef.current.scrollTop=0;if(prevState&&prevState.modal!==this.state.modal){if(this.state.modal){this.modalReturnFocus=document.activeElement;setTimeout(()=>document.querySelector('.modal-head button')?.focus(),0);}else if(this.modalReturnFocus&&document.contains(this.modalReturnFocus))this.modalReturnFocus.focus({preventScroll:true});}}"""))
R.append(("""deepseek-v41-'+mode+'-derived-ledger.json'""",
          """exportLedger(){let mode=this.state.precision;safeDownload('yue2-3b-'+mode+'-ledger.json',JSON.stringify({title:'YuE2-3B - measured safetensors payload ledger',date:'2026-09-15',precision:mode,status:'MEASURED FROM PUBLISHED SHARD HEADERS',notes:['Tensor payload only. File padding, headers, exporter metadata and unknown buffers are excluded.','Quantisation sidecars (weight_scale, weight_global_scale, weight_packed) are folded into their owner weight.','The separate VAE decoder (m-a-p/YuE2-Vae, 0.531 GB) is not part of this checkpoint and is not counted.'],bytes:TOTALS[mode],logicalParameters:TOTAL_P,modules:MODULES.map(m=>({id:m.id,label:m.label,bytes:sumB(m.ws,mode),parameters:sumP(m.ws),weights:m.ws.map(w=>({...w,storageBytes:wBytes(w,mode),displayFormat:wFormat(w,mode)}))})),sources:SOURCES},null,2));this.notify('Byte ledger exported. Every figure is measured from published shard headers.');}"""))
R.append(("""deepseek-v41-3d-""",
          """snapshot(){if(!this.engine)return;const a=document.createElement('a');a.href=this.engine.snapshot();a.download='yue2-3b-3d-'+this.state.view+'.png';a.click();this.notify('3D canvas saved. Interface labels are not part of the canvas.');}"""))
R.append((""" key(e){if(e.ctrlKey||e.metaKey||e.altKey)return;""",
          """ key(e){if(e.ctrlKey||e.metaKey||e.altKey)return;const k=e.key.toLowerCase();if(k==='escape'){if(this.state.modal||this.state.sheet)this.patch({modal:null,sheet:false});else if(this.state.tensor||this.state.expert!==null)this.patch({tensor:null,hoverTensor:null,expert:null});else this.patch({selected:null});return;}if(this.state.modal)return;if(/input|select|textarea/i.test(e.target.tagName))return;if(k===' '){e.preventDefault();this.patch({playing:!this.state.playing});}if(k==='arrowdown'){e.preventDefault();this.walk(1);}if(k==='arrowup'){e.preventDefault();this.walk(-1);}if(k==='+'||k==='='){e.preventDefault();this.changeFont(.1);}if(k==='-'){e.preventDefault();this.changeFont(-.1);}if(k==='b')this.togglePanel();if(k==='t')this.patch({timelineHidden:!this.state.timelineHidden});if(k==='v')this.setLayout(this.state.layout==='tower'?'split':'tower');if(k==='r'&&this.engine){if(this.state.selected)this.engine.focus(this.state.selected);else this.engine.reset();}if(k==='f')this.patch({detailLayout:this.state.detailLayout==='floor'?'column':'floor'});if(k==='x')this.patch({expertView:!this.state.expertView,tensor:null});if(k==='[')this.walkTensor(-1);if(k===']')this.walkTensor(1);if(k==='p'){let keys=MODE_KEYS;this.patch({precision:keys[(keys.indexOf(this.state.precision)+1)%keys.length]});}if(k==='l')this.patch({labels:!this.state.labels});if(k==='k')this.patch({links:!this.state.links});if(['1','2','3'].includes(k))this.setView(['architecture','storage','cache'][Number(k)-1]);}"""))
R.append(("""function moduleExplanation(m){""",
          """function moduleExplanation(m){if(!m)return EXP.overview;if(m.mode)return EXP.overview;if(m.id==='vae')return EXP.bridge;if(m.id==='latent')return EXP.latent;if(m.id==='time')return EXP.time;if(m.id==='embed')return {title:'Token embedding.',body:'184,704 rows at 2048 dims, untied from the head: 756.5 MB at BF16, the shape that makes the vocabulary the second-biggest thing in this checkpoint.'};if(m.id==='head')return {title:'Output head + final norm.',body:'2048 to 184,704 logits in a second 756.5 MB table, plus the final RMSNorm. Untied, and kept wide by both quantised builds.'};return EXP.overview;}"""))
R.append(("""function describeFormat(w){""",
          """function describeFormat(w){return w.note||({bf16:'Two bytes per parameter in the published reference shard.',fp8:'e4m3 weights with a per-tensor weight_scale in the FP8 build.',nvfp4:'4-bit packed weights with both a block scale and a global scale in the NVFP4 build.'}[w.format]||'See the embedded configurations in Sources.');}"""))
R.append(("""function resolveAuditModule(name){""",
          """function resolveAuditModule(name){let n=name.replace(/^(?:language_model\\.|model\\.)+/,'');let b=n.match(/^layers\\.(\\d+)\\./);if(b)return 'L'+b[1];if(/embed_tokens/.test(n))return 'embed';if(/lm_head|^norm\\./.test(n))return 'head';if(/llm2vae|vae2llm/.test(n))return 'vae';if(/latent_pos_embed/.test(n))return 'latent';if(/time_embedder/.test(n))return 'time';return 'Unmapped';}"""))

REWRITES = R

# ---- scene geometry: the residual engine still lays out a 40-layer, sparse-attention model -----------
R.append((""" storage(){let s=this.state,rSide=Math.cbrt(sumB(CATEGORIES[0][3],s.precision)/VOLUME_UNIT),eSide=Math.cbrt(sumB(CATEGORIES[1][3],s.precision)/VOLUME_UNIT),coords=[[-2.6-rSide/2,0,0],[-1.4+eSide/2,0,0],[-1.4+eSide+2.4,0,-2.1],[-1.4+eSide+5.4,0,-2.1],[-1.4+eSide+5.4,0,2],[-1.4+eSide+2.4,0,2],[-4,0,Math.max(rSide,eSide)/2+2.4],[.6,0,Math.max(rSide,eSide)/2+2.4]];""",
          """ storage(){let s=this.state,rSide=Math.cbrt(sumB(CATEGORIES[0][3],s.precision)/VOLUME_UNIT),eSide=Math.cbrt(sumB(CATEGORIES[1][3],s.precision)/VOLUME_UNIT),coords=CATEGORIES.map((c,i)=>{const bb=sumB(c[3],s.precision),sd=Math.cbrt(bb/VOLUME_UNIT);return [(i%3-1)*7.2,0,(Math.floor(i/3)-1)*5.6];});"""))
R.append((""" cache(){const s=this.state,ids=[2,8,14,20];""",
          """ cache(){const s=this.state,ids=[3,10,17,27];"""))
R.append(("""  ids.forEach((id,i)=>{let n=id<20?Math.floor(s.context/2):s.context,b=n*356,p=[(i-1.5)*1.45,1.55,0],side=Math.cbrt(b/VOLUME_UNIT);this.emit('kv:'+id,p,b,i===3?COL.dec:COL.full,{module:'L'+id,label:'L'+id+' global KV + index keys',bytes:b},{glow:.12});this.label([p[0],2.0+side/2,0],'L'+String(id).padStart(2,'0'),(id<20?'2:1 / ':'1:1 / ')+bytes(b,s.binary),i===3?COL.dec:COL.full,5);if(s.links)this.curve([p[0],1.2,0],[0,-.2,0],i===3?COL.dec:COL.full,.3,i*.18,.6,2);});""",
          """  ids.forEach((id,i)=>{const per=KV_FULL_PER_TOKEN/28*(s.precision==='bf16'?1:.5);let n=s.context,b=n*per,p=[(i-1.5)*1.45,1.55,0],side=Math.cbrt(b/VOLUME_UNIT);this.emit('kv:'+id,p,b,i===3?COL.dec:COL.full,{module:'L'+id,label:'L'+id+' KV cache / 8 heads x 128 dims',bytes:b},{glow:.12});this.label([p[0],2.0+side/2,0],'L'+String(id).padStart(2,'0'),bytes(b,s.binary),i===3?COL.dec:COL.full,5);if(s.links)this.curve([p[0],1.2,0],[0,-.2,0],i===3?COL.dec:COL.full,.3,i*.18,.6,2);});"""))
R.append(("""  const selected=pickExperts(Math.floor(this.clock*.4),2048,512),set=new Set(selected);""",
          """   const frames=2048,set=new Set([frames-1]);"""))
R.append(("""  for(let i=0;i<2048;i++){let x=(i%64-31.5)*.077,y=-.5-Math.floor(i/64)*.052;this.point([x,y,0],set.has(i)?COL.dec:'#4a6280',set.has(i)?3.3:2,set.has(i)?.72:.22);}""",
          """   for(let i=0;i<frames;i++){let x=(i%64-31.5)*.077,y=-.5-Math.floor(i/64)*.052;this.point([x,y,0],set.has(i)?COL.dec:'#4a6280',set.has(i)?3.3:2,set.has(i)?.72:.22);}"""))
R.append(("""  this.label([0,-2.53,0],'2,048 CANDIDATE BLOCKS x 8','A schematic pool; the true cap is 16,384 candidate positions.',COL.muted,7);""",
          """  this.label([0,-2.53,0],'2,048 OF 24,576 LATENT FRAMES','The timeline is what this checkpoint reads: 24,576 frames maximum, and no layer is sparse or recurrent.',COL.muted,7);"""))

R.append(("""  <details class="account-details"><summary>${bytes(b.total,s.binary)} stored payload <span>Show the arithmetic</span></summary>""",
          """  ${wBytes(w,s.precision)===0&&html`<p class="fine"><b>Not converted in this build.</b> This tensor is absent from the ${MODE_INFO[s.precision].label} payload, so no bytes are counted for it in this mode; the reference stores it at BF16.</p>`}  <details class="account-details"><summary>${bytes(b.total,s.binary)} stored payload <span>Show the arithmetic</span></summary><${Fact} label="Logical parameters" value=${fmtP(v.p)}/><${Fact} label="Packed data" value=${bytes(b.data,s.binary)}/><${Fact} label="Group / block scales" value=${b.scales?bytes(b.scales,s.binary):'None in this model'}/>${b.aux>0&&html`<${Fact} label="Tensor-level scales (estimate)" value=${num(b.aux)+' B'}/>`}<${Fact} label="Total" value=${num(b.total)+' B'}/><p class="fine">Matrix shapes are [output, input]. Volumes include modeled scales. Exact checkpoint dtypes, metadata and padding require a shard-header audit.</p></details>"""))
